name: swf_player_example
description: Example app for the swf_player package.
publish_to: none
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  swf_player:
    path: ../
  swf_core: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
