name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  swf_core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
        working-directory: packages/swf_core
      - run: dart format --output=none --set-exit-if-changed .
        working-directory: packages/swf_core
      - run: dart analyze --fatal-infos
        working-directory: packages/swf_core
      - run: dart test
        working-directory: packages/swf_core

  swf_player:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
        working-directory: packages/swf_player
      - run: flutter analyze
        working-directory: packages/swf_player
      - run: flutter test
        working-directory: packages/swf_player
      - run: flutter test
        working-directory: packages/swf_player/example
